# Generated by Django 5.1.4 on 2026-09-22 06:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaySession',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(default='Day 1', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('venue', models.CharField(default='Convention Center Arena & Lab A', max_length=255)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('table', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('not_scanned', 'Not Checked In'), ('present', 'Checked In / Present'), ('absent', 'Absent')], default='not_scanned', max_length=32)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('marked_by', models.CharField(blank=True, max_length=64, null=True)),
                ('override_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('table_number', models.CharField(default='Table 01', max_length=64)),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovementPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type', models.CharField(choices=[('WASHROOM', 'Washroom (10m)'), ('FOOD_PICKUP', 'Food Pickup (20m)'), ('REST_BREAK', 'Rest Break (45m)'), ('LEFT_VENUE', 'Left Venue (60m)')], default='WASHROOM', max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('depart_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('force_closed', 'Force Closed')], default='active', max_length=32)),
                ('closed_by', models.CharField(blank=True, max_length=64, null=True)),
                ('day_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes', to='api.daysession')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='api.participant')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.team'),
        ),
        migrations.CreateModel(
            name='MentorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=128)),
                ('participant_name', models.CharField(max_length=128)),
                ('table', models.CharField(default='Table 01', max_length=64)),
                ('topic', models.TextField()),
                ('category', models.CharField(default='General Tech', max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('resolved', 'Resolved')], default='open', max_length=32)),
                ('mentor_assigned', models.CharField(blank=True, max_length=128, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_requests', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=128)),
                ('participant_name', models.CharField(default='Desk', max_length=128)),
                ('table', models.CharField(default='Table 01', max_length=64)),
                ('items', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dietary', models.CharField(default='Standard', max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered')], default='pending', max_length=32)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_requests', to='api.team')),
            ],
        ),
    ]
